import {extendExplorationConfig} from './exploration-config.mjs';
import {extendDirectorConfig} from './director-config.mjs';
import { promises as fs } from 'node:fs';
export async function loadConfig(file) {
  const config = JSON.parse(await fs.readFile(file, 'utf8'));
  config.unarmed??={"id":"fist","damage":8,"range":1.25,"arc_deg":60,"cooldown_seconds":0.6,"windup_seconds":0.16};
  const unarmed=config.unarmed;
  if(!unarmed||typeof unarmed!=='object'||Array.isArray(unarmed)||(unarmed.id!==undefined&&unarmed.id!=='fist')||['damage','range','arc_deg','cooldown_seconds','windup_seconds'].some(k=>!Number.isFinite(unarmed[k])||unarmed[k]<=0)||unarmed.arc_deg>180||unarmed.windup_seconds>unarmed.cooldown_seconds)throw Error('Invalid unarmed config');
  for (const key of ['player','cycle','session','economy','fishing','construction','recovery','level']) if (!config[key]) throw Error(`Missing config ${key}`);
  if(['downed_hp','downed_seconds','downed_min_seconds','downed_repeat_penalty','downed_grace_seconds','crawl_speed','self_revive_quiet_seconds','self_revive_seconds','self_revive_hp','revive_seconds','revive_hp'].some(k=>!Number.isFinite(config.player[k])||config.player[k]<=0)||config.player.downed_min_seconds>config.player.downed_seconds||config.player.crawl_speed>=config.player.walk_speed||config.player.revive_hp>config.player.max_hp||config.player.self_revive_hp>config.player.max_hp)throw Error('Invalid downed rescue config');
  const terminals=config.level.terminals;
  const stationTypes={terminal:'shop',storage:'storage',emergency_tools:'shop',emergency_storage:'storage',upgrade:'upgrade',recycle:'recycle',emergency_upgrade:'upgrade',emergency_recycle:'recycle'};
  if(!Array.isArray(terminals)||terminals.length!==8||new Set(terminals.map(t=>t?.id)).size!==terminals.length||terminals.some(t=>!t||typeof t.id!=='string'||!Object.hasOwn(stationTypes,t.id)||stationTypes[t.id]!==t.type||!Number.isFinite(t.x)||!Number.isFinite(t.z)||typeof t.label!=='string'||!t.label.length||t.label.length>4||(t.type==='storage'&&t.containerId!=='storage')))throw Error('Invalid station layout');
  for (const key of ['items','weapons','rods','creatures','buildings','waves']) {
    if (!Array.isArray(config[key]) || new Set(config[key].map(x => x.id ?? x.stage)).size !== config[key].length) throw Error(`Invalid config ${key}`);
  }
  config.fishing.open_water??={weights:[{creature:'silverfish',weight:70},{creature:'crab',weight:25},{creature:'eel',weight:5}],max_alive_per_player:2,loot:'catch_shore',hp:{silverfish:18,crab:28,eel:32},damage:3,speed:1.8,aggro_range:4,leash_range:6,attack_range:1.2,attack_windup:.7,attack_cooldown:1.6};
  if(!config.items.some(item=>item.id==='catch_shore'))config.items.push({id:'catch_shore',name:'小型渔获',kind:'catch',stack:5,sell_c:8});
  if(!config.items.some(item=>item.id==='boss_trophy'))config.items.push({id:'boss_trophy',name:'首领战利品',kind:'catch',stack:5,sell_c:180});
  config.cycle.night_survival_seconds??=180;
  config.recovery.day_seconds??=420;config.recovery.streak_extra_seconds??=90;config.recovery.max_day_seconds??=600;
  config.encounters.nightly_boss??={base_hp:600,hp_daily_growth:.08,hp_growth_cap:3,count_daily_growth:.03,count_growth_cap:1.6,reward_item:'boss_trophy',reward_scrap:20,player_proximity:3};
  const boss=config.encounters.nightly_boss;
  if(['night_survival_seconds'].some(k=>!Number.isFinite(config.cycle[k])||config.cycle[k]<=0)||['day_seconds','streak_extra_seconds','max_day_seconds'].some(k=>!Number.isFinite(config.recovery[k])||config.recovery[k]<=0)||!config.items.some(i=>i.id===boss.reward_item)||['base_hp','hp_daily_growth','hp_growth_cap','count_daily_growth','count_growth_cap','reward_scrap','player_proximity'].some(k=>!Number.isFinite(boss[k])||boss[k]<=0))throw Error('Invalid survival cycle config');
  config.encounters.danger_zones??=[{id:'salvage',label:'残骸搜刮区',radius:24},{id:'hunt',label:'礁滩狩猎区',radius:24},{id:'supply',label:'废弃补给区',radius:24}];
  config.encounters.guard_alert??={search_radius:22,shot_radius:40,investigate_seconds:8,patrol_radius:4,leash_range:32};
  config.encounters.night_pressure??=[{players:1,alive_cap:5,spawn_interval:4},{players:2,alive_cap:8,spawn_interval:3},{players:4,alive_cap:14,spawn_interval:2},{players:8,alive_cap:24,spawn_interval:1.5}];
  config.fortress??={slots:[{id:'T01',x:-8,z:-8},{id:'T02',x:8,z:8}],unlock:{coreLevel:2,daysSurvived:2},muzzleHeight:3.6,range:27,shotInterval:1,levels:[{level:1,hp:250,damage:10,capacity:60},{level:2,hp:400,damage:14,capacity:80}],costs:{install:{credits:160,materials:30,seconds:6},rebuild:{credits:80,materials:20,seconds:6},upgrade:{credits:120,materials:25,seconds:4},reload:{credits:0,materials:10,seconds:4}},collision:[{x:0,y:.6,z:0,width:.95,height:1.2,depth:.95},{x:0,y:2.25,z:0,width:.3,height:2.1,depth:.3},{x:0,y:3.575,z:0,width:.9,height:.55,depth:.9}]};
  const fortress=config.fortress;
  if(!Array.isArray(config.encounters.night_pressure)||config.encounters.night_pressure.length!==4||config.encounters.night_pressure.some((p,i)=>p.players!==[1,2,4,8][i]||!Number.isInteger(p.alive_cap)||p.alive_cap<1||p.alive_cap>24||!Number.isFinite(p.spawn_interval)||p.spawn_interval<=0))throw Error('Invalid night pressure config');
  if(!Array.isArray(fortress.slots)||fortress.slots.length!==2||new Set(fortress.slots.map(s=>s.id)).size!==2||fortress.slots.some(s=>!Number.isFinite(s.x)||!Number.isFinite(s.z))||fortress.levels.length!==2||fortress.levels.some((l,i)=>l.level!==i+1||!Number.isFinite(l.hp)||l.hp<=0||!Number.isFinite(l.damage)||l.damage<=0||!Number.isSafeInteger(l.capacity)||l.capacity<1)||['install','rebuild','upgrade','reload'].some(k=>!fortress.costs[k]||['credits','materials','seconds'].some(f=>!Number.isFinite(fortress.costs[k][f])||fortress.costs[k][f]<(f==='seconds'?.01:0)))||!Number.isFinite(fortress.range)||fortress.range<=0||!Number.isFinite(fortress.shotInterval)||fortress.shotInterval<=0)throw Error('Invalid fortress config');
  const sea=config.fishing.open_water,alert=config.encounters.guard_alert;
  if(!Array.isArray(sea.weights)||!sea.weights.length||sea.weights.some(w=>!config.creatures.some(c=>c.id===w.creature)||!Number.isFinite(w.weight)||w.weight<=0)||!config.items.some(i=>i.id===sea.loot)||!Number.isInteger(sea.max_alive_per_player)||sea.max_alive_per_player<1||sea.max_alive_per_player>2||['damage','speed','aggro_range','leash_range','attack_range','attack_windup','attack_cooldown'].some(k=>!Number.isFinite(sea[k])||sea[k]<=0)||sea.weights.some(w=>!Number.isFinite(sea.hp[w.creature])||sea.hp[w.creature]<=0))throw Error('Invalid open water fishing config');
  if(!config.encounters.danger_zones.length||config.encounters.danger_zones.some(z=>!config.level.locations.some(l=>l.id===z.id)||!Number.isFinite(z.radius)||z.radius<=0)||['search_radius','shot_radius','investigate_seconds','patrol_radius','leash_range'].some(k=>!Number.isFinite(alert[k])||alert[k]<=0))throw Error('Invalid guard config');
  for (const weapon of config.weapons) if (!config.items.some(x => x.id === weapon.id) || !config.items.some(x => x.id === weapon.ammo)) throw Error('Invalid weapon references');
  for (const rod of config.rods) if (!config.items.some(x => x.id === rod.id && x.kind === 'rod')) throw Error(`Invalid rod item reference: ${rod.id}`);
  for (const creature of config.creatures) if (creature.loot && !config.items.some(x => x.id === creature.loot)) throw Error(`Invalid creature loot reference: ${creature.id}`);
  for (const id of [...config.economy.start_loadout,...config.economy.free_recovery_tools]) if (!config.items.some(x => x.id === id)) throw Error(`Invalid economy item reference: ${id}`);
  if(config.economy.gear_resale && (!Number.isFinite(config.economy.resale_upgrade_fraction)||config.economy.resale_upgrade_fraction<0||config.economy.resale_upgrade_fraction>1||config.items.some(item=>!['catch','loot','material'].includes(item.kind)&&(!Number.isSafeInteger(item.resale_c)||item.resale_c<=0))))throw Error('Invalid resale config');
  for (const pool of config.fishing.pools) for (const weight of pool.weights) if (!config.creatures.some(x => x.id === weight.creature) || weight.weight <= 0) throw Error(`Invalid fishing creature reference: ${pool.id}`);
  for (const item of config.items) if (!Number.isSafeInteger(item.stack) || item.stack < 1 || ['buy_c','buy_m','sell_c','deposit_m','resale_c'].some(key => item[key] !== undefined && (!Number.isFinite(item[key]) || item[key] < 0))) throw Error(`Invalid item values: ${item.id}`);
  config.baseline??={};config.baseline.max_players??=8;
  if (![4,8].includes(config.baseline.max_players) || config.session.server_hz < 1 || config.session.save_interval_seconds <= 0 || !Number.isInteger(config.encounters.night_alive_cap) || config.encounters.night_alive_cap<1 || config.encounters.night_alive_cap>24) throw Error('Invalid session config');
  for(const weapon of config.weapons){
    if(['ads_seconds','equip_seconds'].some(k=>weapon[k]!==undefined&&(!Number.isFinite(weapon[k])||weapon[k]<=0||weapon[k]>2))||(weapon.move_spread_deg!==undefined&&(!Number.isFinite(weapon.move_spread_deg)||weapon.move_spread_deg<0||weapon.move_spread_deg>10)))throw Error('Invalid weapon handling '+weapon.id);
    if(!['auto','semi','pump','bolt'].includes(weapon.fire_mode)||['damage','pellets','rpm','magazine','reload_seconds','range_full','range_end','range_end_multiplier','hip_spread_deg','ads_spread_deg','recoil_pitch_deg','recoil_yaw_deg','ads_fov'].some(k=>!Number.isFinite(weapon[k])||weapon[k]<=0)||!Number.isSafeInteger(weapon.magazine)||!Number.isSafeInteger(weapon.pellets)||weapon.range_end<=weapon.range_full||weapon.range_end_multiplier>1||(weapon.move_multiplier!==undefined&&(!Number.isFinite(weapon.move_multiplier)||weapon.move_multiplier<=0||weapon.move_multiplier>1)))throw Error('Invalid weapon behavior '+weapon.id);
  }
  for(const rod of config.rods){
    if(['cast_range','reel_power','tension_rise','tension_fall'].some(k=>!Number.isFinite(rod[k])||rod[k]<=0)||['charge_seconds','cast_seconds','bite_wait_min','bite_wait_max','struggle_multiplier','hook_window_seconds','reel_timeout_seconds'].some(k=>rod[k]!==undefined&&(!Number.isFinite(rod[k])||rod[k]<=0))||(rod.bite_wait_min??config.fishing.bite_wait_min)>(rod.bite_wait_max??config.fishing.bite_wait_max)||rod.catch_kind!==undefined&&rod.catch_kind!=='salvage')throw Error('Invalid rod behavior '+rod.id);
    if(rod.catch_kind==='salvage'&&(!Number.isSafeInteger(rod.max_unclaimed)||rod.max_unclaimed<1||rod.max_unclaimed>2||!Array.isArray(rod.loot_table)||!rod.loot_table.length||rod.loot_table.some(e=>{const item=config.items.find(i=>i.id===e.definitionId);return !item||!['material','ammo','loot'].includes(item.kind)||!Number.isSafeInteger(e.quantity)||e.quantity<1||e.quantity>item.stack||!Number.isFinite(e.weight)||e.weight<=0||!Number.isFinite(e.resistance)||e.resistance<=0;})))throw Error('Invalid salvage rod '+rod.id);
  }
  const extended=extendExplorationConfig(extendDirectorConfig(config));
  const destructibles=extended.destructibles,types=destructibles?.types,archive=destructibles?.archive;
  const expectedTypes=['crate','barrel','barricade','partition_panel','archive_cabinet'];
  if(!destructibles||!Number.isSafeInteger(destructibles.total_count)||destructibles.total_count!==36||!Array.isArray(types)||types.length!==expectedTypes.length||new Set(types.map(x=>x?.id)).size!==types.length||expectedTypes.some(id=>!types.some(x=>x.id===id))||types.some(type=>!Number.isSafeInteger(type.count)||type.count<1||!Number.isFinite(type.hp)||type.hp<=0||!['wood','metal'].includes(type.material)||!type.size||['x','y','z'].some(axis=>!Number.isFinite(type.size[axis])||type.size[axis]<=0))||types.reduce((sum,type)=>sum+type.count,0)!==destructibles.total_count||types.find(type=>type.id==='crate').count<4||types.find(type=>type.id==='partition_panel').count!==6)throw Error('Invalid destructible config');
  const rewardTables=[archive?.searched_rewards,archive?.smashed_rewards];
  if(!archive||!Number.isFinite(archive.search_seconds)||archive.search_seconds<=0||archive.search_seconds>10||!Number.isFinite(archive.search_radius)||archive.search_radius<=0||!Number.isFinite(archive.break_radius)||archive.break_radius<archive.search_radius||rewardTables.some(table=>!Array.isArray(table)||!table.length||table.some(row=>!Array.isArray(row)||!row.length||row.some(reward=>{const item=extended.items.find(candidate=>candidate.id===reward?.definitionId);return !item||!Number.isSafeInteger(reward.quantity)||reward.quantity<1||reward.quantity>item.stack;}))))throw Error('Invalid archive cabinet config');
  return extended;
}
